fix(@sap-ux/fe-mockserver-core): implicitly expand navigation properties used in a filter expression
SAP/open-ux-odata pull request #383
Opened 2023-01-03 16:25 UTC by drktfl

This PR fixes a limitation on `$filter` expressions. In order to properly apply the filter condition, all data must be available at the time the filter is evaluated. This was only the case when the client requested that data by a corresponding `$expand` parameter.

That is,

`/Entities?$filter=navigationProperty2/value eq 0` and
`/Entities?$filter=navigationProperty2/value eq 0&$expand=navigationProperty2`
probably resulted in a different number of entries.

The mockserver now makes sure that the required data is available to the filters.

2023-01-03 17:00 UTC, drktfl reviewed
do not merge, needs some more work

2023-01-04 09:57 UTC, nlunets requested changes

2023-01-04 09:57 UTC, nlunets commented on packages/fe-mockserver-core/src/data/entitySets/entitySet.ts
> +                return mockDataToCheckValue.every(check);
this looks indeed better :P

2023-01-04 09:57 UTC, nlunets commented on packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts
> +    describe('additional $filter tests', () => {
While this test is interesting to test the result of the filtering, i would also like to see a test for the `addExpandForFilters` case (maybe indirectly just through some test in the odataRequest) to validate that the filter expressions are properly taken into account, and also to check what happens when you have select + expand + filter.

2023-01-10 09:20 UTC, nlunets approved these changes

2023-01-10 09:21 UTC, nlunets approved these changes

2023-01-10 09:27 UTC, nlunets commented on packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts
> +    describe('additional $filter tests', () => {
Sounds good now

2023-01-10 09:30 UTC, merged